# Generated by Django 6.0.5 on 2026-06-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomment',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
